/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#333539',
        'surface': '#111318',
        'on-surface-variant': '#c2c7d0',
        'on-primary-fixed-variant': '#184974',
        'on-tertiary': '#003354',
        'tertiary-fixed-dim': '#98cbff',
        'inverse-on-surface': '#2f3035',
        'primary': '#a0cafc',
        'on-surface': '#e2e2e8',
        'error': '#ffb4ab',
        'outline-variant': '#42474f',
        'surface-container-highest': '#333539',
        'inverse-surface': '#e2e2e8',
        'on-primary-container': '#95bff1',
        'secondary-container': '#00a693',
        'on-secondary-fixed': '#00201b',
        'surface-container': '#1e2024',
        'surface-bright': '#37393e',
        'on-primary': '#003257',
        'on-secondary': '#003730',
        'primary-fixed-dim': '#a0cafc',
        'on-error': '#690005',
        'surface-container-low': '#1a1c20',
        'tertiary-container': '#004f7e',
        'on-background': '#e2e2e8',
        'outline': '#8c9199',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-tertiary-container': '#86c1fa',
        'surface-container-high': '#282a2e',
        'surface-tint': '#a0cafc',
        'background': '#111318',
        'tertiary-fixed': '#cee5ff',
        'secondary-fixed': '#7af7e1',
        'on-tertiary-fixed-variant': '#004a77',
        'surface-container-lowest': '#0c0e12',
        'inverse-primary': '#35618d',
        'on-secondary-fixed-variant': '#005046',
        'surface-dim': '#111318',
        'primary-fixed': '#d1e4ff',
        'secondary-fixed-dim': '#5bdac6',
        'secondary': '#5bdac6',
        'tertiary': '#98cbff',
        'on-primary-fixed': '#001d35',
        'on-tertiary-fixed': '#001d33',
        'primary-container': '#1f4e79',
        'on-secondary-container': '#00332c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'unit': '8px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'gutter': '24px',
        'hit-area-min': '80px',
      },
      fontFamily: {
        'display': ['Manrope', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'body-md': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-caps': ['14px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
